name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY }}

    - name: Test SSH connection
      run: ssh -o StrictHostKeyChecking=no root@170.64.166.103 'echo "SSH connection successful"'

    - name: Deploy script
      run: ssh -o StrictHostKeyChecking=no root@170.64.166.103 'java -jar root/deploy.xml'
